-- ▄    ▄▄▄  ▄▄ ▄▄  ▄▄▄▄ ▄▄▄▄▄▄ ▄▄    
--  ▀▄ ██▀██ ▀█▄█▀ ██▀▀▀   ██   ██    
-- ▄▀  ██▀██ ██ ██ ▀████   ██   ██▄▄▄ 

hl.on("hyprland.start", function()
    hl.exec_cmd("ambxst")
end)


-- ▄    ▄▄▄  ▄▄ ▄▄  ▄▄▄▄ ▄▄▄▄▄▄ ▄▄    
--  ▀▄ ██▀██ ▀█▄█▀ ██▀▀▀   ██   ██    
-- ▄▀  ██▀██ ██ ██ ▀████   ██   ██▄▄▄ 

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 4,
        border_size = 2,
        col = {
            active_border = "rgb(82d3e2)",
            inactive_border = "rgb(1e2224)",
        },
        layout = "dwindle",
    },
    decoration = {
        rounding = 17,
        active_opacity = 1.00,
        inactive_opacity = 1.00,
        shadow = {
            enabled = true,
            range = 8,
            color = "rgba(00000080)",
        },
        blur = {
            enabled = true,
            size = 4,
            passes = 2,
        },
    },
})

hl.config({
    animations = { enabled = true },
})

hl.curve("myBezier", { type = "bezier", points = { {0.4, 0.0}, {0.2, 1.0} } })

hl.animation({ leaf = "windows", enabled = true, speed = 2.5, bezier = "myBezier", style = "popin 80%" })
hl.animation({ leaf = "border", enabled = true, speed = 2.5, bezier = "myBezier" })
hl.animation({ leaf = "fade", enabled = true, speed = 2.5, bezier = "myBezier" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.5, bezier = "myBezier", style = "slidefade 20%" })

-- Generated by axctl LuaGenerator (Keybinds)
-- Do not edit manually!

hl.bind("SUPER + Super_L", hl.dsp.exec_cmd("ambxst run launcher"))
hl.bind("SUPER + D", hl.dsp.exec_cmd("ambxst run dashboard"))
hl.bind("SUPER + A", hl.dsp.exec_cmd("ambxst run assistant"))
hl.bind("SUPER + C", hl.dsp.exec_cmd("ambxst run clipboard"))
hl.bind("SUPER + PERIOD", hl.dsp.exec_cmd("ambxst run emoji"))
hl.bind("SUPER + N", hl.dsp.exec_cmd("ambxst run notes"))
hl.bind("SUPER + U", hl.dsp.exec_cmd("ambxst run tmux"))
hl.bind("SUPER + W", hl.dsp.exec_cmd("ambxst run wallpapers"))
hl.bind("SUPER + TAB", hl.dsp.exec_cmd("ambxst run overview"))
hl.bind("SUPER + ESCAPE", hl.dsp.exec_cmd("ambxst run powermenu"))
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("ambxst run config"))
hl.bind("SUPER + L", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind("SUPER + S", hl.dsp.exec_cmd("ambxst run tools"))
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("ambxst run screenshot"))
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("ambxst run lens"))
hl.bind("SUPER + ALT + B", hl.dsp.exec_cmd("ambxst reload"))
hl.bind("SUPER + CTRL + ALT + B", hl.dsp.exec_cmd("ambxst quit"))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = "2" }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = "3" }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = "4" }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = "5" }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = "6" }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = "7" }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = "8" }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = "9" }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "10" }))
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = "1" }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = "2" }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = "3" }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = "4" }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = "5" }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = "6" }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = "7" }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = "8" }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = "9" }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "10" }))
hl.bind("SUPER + ALT + 1", hl.dsp.window.move({ workspace = "1" }))
hl.bind("SUPER + ALT + 2", hl.dsp.window.move({ workspace = "2" }))
hl.bind("SUPER + ALT + 3", hl.dsp.window.move({ workspace = "3" }))
hl.bind("SUPER + ALT + 4", hl.dsp.window.move({ workspace = "4" }))
hl.bind("SUPER + ALT + 5", hl.dsp.window.move({ workspace = "5" }))
hl.bind("SUPER + ALT + 6", hl.dsp.window.move({ workspace = "6" }))
hl.bind("SUPER + ALT + 7", hl.dsp.window.move({ workspace = "7" }))
hl.bind("SUPER + ALT + 8", hl.dsp.window.move({ workspace = "8" }))
hl.bind("SUPER + ALT + 9", hl.dsp.window.move({ workspace = "9" }))
hl.bind("SUPER + ALT + 0", hl.dsp.window.move({ workspace = "10" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + SHIFT + Z", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + SHIFT + X", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + Z", hl.dsp.focus({ workspace = "-1" }))
hl.bind("SUPER + X", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioMedia", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%-"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("ambxst brightness +5"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("ambxst brightness -5"))
hl.bind("XF86Calculator", hl.dsp.exec_cmd("notify-send \"Soon\""))
hl.bind("SUPER + V", hl.dsp.workspace.toggle_special(""))
hl.bind("SUPER + SHIFT + V", hl.dsp.window.move({ workspace = "special" }))
hl.bind("switch:Lid Switch", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("axctl monitor set-dpms 0 0"))
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("axctl monitor set-dpms 0 1"))
hl.bind("SUPER + Up", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("focus u")) else hl.dispatch(hl.dsp.focus({ direction = "u" })) end end)
hl.bind("SUPER + CTRL + k", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("focus u")) else hl.dispatch(hl.dsp.focus({ direction = "u" })) end end)
hl.bind("SUPER + Down", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("focus d")) else hl.dispatch(hl.dsp.focus({ direction = "d" })) end end)
hl.bind("SUPER + CTRL + j", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("focus d")) else hl.dispatch(hl.dsp.focus({ direction = "d" })) end end)
hl.bind("SUPER + Left", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("focus l")) else hl.dispatch(hl.dsp.focus({ direction = "l" })) end end)
hl.bind("SUPER + CTRL + z", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("focus l")) else hl.dispatch(hl.dsp.focus({ direction = "l" })) end end)
hl.bind("SUPER + CTRL + h", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("focus l")) else hl.dispatch(hl.dsp.focus({ direction = "l" })) end end)
hl.bind("SUPER + Right", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("focus r")) else hl.dispatch(hl.dsp.focus({ direction = "r" })) end end)
hl.bind("SUPER + CTRL + x", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("focus r")) else hl.dispatch(hl.dsp.focus({ direction = "r" })) end end)
hl.bind("SUPER + CTRL + l", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("focus r")) else hl.dispatch(hl.dsp.focus({ direction = "r" })) end end)
hl.bind("SUPER + SHIFT + Left", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + h", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + Right", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT + l", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT + Up", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + k", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + Down", hl.dsp.window.move({ direction = "d" }))
hl.bind("SUPER + SHIFT + j", hl.dsp.window.move({ direction = "d" }))
hl.bind("SUPER + ALT + Right", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("colresize +0.1")) end end)
hl.bind("SUPER + ALT + l", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("colresize +0.1")) end end)
hl.bind("SUPER + ALT + Left", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("colresize -0.1")) end end)
hl.bind("SUPER + ALT + h", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("colresize -0.1")) end end)
hl.bind("SUPER + ALT + Down", hl.dsp.exec_cmd("resizeactive 0 50"))
hl.bind("SUPER + ALT + j", hl.dsp.exec_cmd("resizeactive 0 50"))
hl.bind("SUPER + ALT + Up", hl.dsp.exec_cmd("resizeactive 0 -50"))
hl.bind("SUPER + ALT + k", hl.dsp.exec_cmd("resizeactive 0 -50"))
hl.bind("SUPER + ALT + SPACE", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("promote")) end end)
hl.bind("SUPER + CTRL + SPACE", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("togglefit")) end end)
hl.bind("SUPER + SHIFT + SPACE", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("colresize +conf")) end end)
hl.bind("SUPER + ALT + CTRL + Left", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("swapcol l")) end end)
hl.bind("SUPER + ALT + CTRL + h", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("swapcol l")) end end)
hl.bind("SUPER + ALT + CTRL + Right", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("swapcol r")) end end)
hl.bind("SUPER + ALT + CTRL + l", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("swapcol r")) end end)
hl.bind("SUPER + CTRL + ALT + 1", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("movecoltoworkspace 1")) end end)
hl.bind("SUPER + CTRL + ALT + 2", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("movecoltoworkspace 2")) end end)
hl.bind("SUPER + CTRL + ALT + 3", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("movecoltoworkspace 3")) end end)
hl.bind("SUPER + CTRL + ALT + 4", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("movecoltoworkspace 4")) end end)
hl.bind("SUPER + CTRL + ALT + 5", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("movecoltoworkspace 5")) end end)
hl.bind("SUPER + CTRL + ALT + 6", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("movecoltoworkspace 6")) end end)
hl.bind("SUPER + CTRL + ALT + 7", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("movecoltoworkspace 7")) end end)
hl.bind("SUPER + CTRL + ALT + 8", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("movecoltoworkspace 8")) end end)
hl.bind("SUPER + CTRL + ALT + 9", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("movecoltoworkspace 9")) end end)
hl.bind("SUPER + CTRL + ALT + 0", function() if hl.get_active_workspace().tiled_layout == "scrolling" then hl.dispatch(hl.dsp.layout("movecoltoworkspace 10")) end end)
hl.bind("SUPER + Space", hl.dsp.exec_cmd("ghostty"))
hl.bind("SUPER + E", hl.dsp.exec_cmd("firefox"))
hl.bind("SUPER + B", hl.dsp.exec_cmd("thunar"))
hl.bind("SHIFT + SUPER + W", hl.dsp.exec_cmd("ls ~/.local/src/ambxst/scripts/"))
hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd("bash ~/.config/scripts/rice-switcher.sh"))
hl.bind("SUPER + F", hl.dsp.exec_cmd("hyprctl dispatch fullscreen"))
hl.bind("SUPER + T", hl.dsp.exec_cmd("hyprctl dispatch togglefloating"))
hl.bind("SUPER + R", hl.dsp.exec_cmd("bash ~/.config/scripts/record-toggle.sh"))

-- Generated by axctl LuaGenerator (Window Rules)
-- Do not edit manually!


-- Generated by axctl LuaGenerator (Layer Rules)
-- Do not edit manually!

hl.layer_rule({
    no_anim = true,
    match = { namespace = "quickshell" },
})

hl.layer_rule({
    blur = true,
    match = { namespace = "quickshell" },
})

hl.layer_rule({
    blur_popups = true,
    match = { namespace = "quickshell" },
})

hl.layer_rule({
    ignore_alpha = 1.00,
    match = { namespace = "quickshell" },
})

hl.layer_rule({
    no_anim = true,
    match = { namespace = "selection" },
})

hl.layer_rule({
    blur = true,
    ignore_alpha = 0.40,
    match = { namespace = "fabric" },
})

hl.layer_rule({
    no_anim = true,
    blur = true,
    blur_popups = true,
    ignore_alpha = 0.50,
    match = { namespace = "ambxst" },
})

hl.layer_rule({
    no_anim = true,
    blur = true,
    blur_popups = true,
    match = { namespace = "overview" },
})

hl.layer_rule({
    no_anim = true,
    blur = true,
    blur_popups = true,
    match = { namespace = "presets" },
})

