
# --- custom keybind overrides ---
$kbTerminal = Super, Space
$kbBrowser = Super, E
$kbFileExplorer = Super, B
$kbToggleWindowFloating = Super, T
$kbToggleSpecialWs = Super, V
$kbMoveWinToWs = Super+Shift
$browser = firefox
