# --- custom new keybinds ---
bind = Super, D, global, caelestia:dashboard
bind = Super, W, exec, caelestia wallpaper -r ~/wallpapers/
windowrule = opacity 1.0 0.95 override, match:fullscreen false

# clipboard moved to Super+/ (frees Super+V for special workspace)
unbind = Super, V
bind = Super, V, exec, caelestia toggle specialws
bind = Super, slash, exec, pkill fuzzel || caelestia clipboard

# settings (nexus) toggle open/close
bind = Super, A, exec, hyprctl clients | grep -q Nexus && hyprctl dispatch closewindow title:Nexus || caelestia shell nexus open
