
# --- custom new keybinds ---
bind = Super, D, global, caelestia:dashboard
bind = Super, A, global, caelestia:nexus
bind = Super, W, exec, caelestia wallpaper -r ~/wallpapers/
windowrule = opacity 1.0 0.95 override, match:fullscreen false
